### ISSUE TITLE
BasePath directory not created when outside the current providers directory

### ISSUE THREAD

**Issue by DoCode** [adams85/filelogger#1]
When BasePath is relative upwards the current file providers directory then the directory and logs not created.

Sample:
```json
  "logging": {
    "BasePath": "..\\appdata\\logs",
    "EnsureBasePath": true,
    // ...
```

**Comment by adams85** [comment]
This is the expected behavior as default implementation is built on the top of PhysicalFileProvider. This is explained in the [MSDN docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers#physicalfileprovider): "When instantiating this provider, you must provide it with a directory path, which serves as the base path for all requests made to this provider (and which restricts access outside of this path)."

Anyway, readme docs is updated to remark on this.
