### ISSUE TITLE
Is Karambolo thread-safe?

### ISSUE THREAD

**Issue by aleksvujic** [adams85/filelogger#23]
Is Karambolo file logging provider **thread safe**? What happens if two threads try to log a message at the same time?

**Comment by adams85** [comment]
The logger is, of course, thread-safe. It uses [System.Threading.Channels](https://devblogs.microsoft.com/dotnet/an-introduction-to-system-threading-channels/) for implementing the producer/consumer pattern where a queue is maintained per each log file. Your log entries are [written into the corresponding log file's queue](https://github.com/adams85/filelogger/blob/5be852456ab7f672a1806fca1b73c6fda2550aa8/source/FileLogger/FileLogger.cs#L181) (which is a thread-safe operation by design), and there is a consumer process (running on the thread pool) which [reads these entries and writes them to the log file](https://github.com/adams85/filelogger/blob/5be852456ab7f672a1806fca1b73c6fda2550aa8/source/FileLogger/FileLoggerProcessor.cs#L516-L519) one after the other.

Does this answer your question?
